
package aa.bb.cc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.1
 * Fri Nov 24 09:53:39 CST 2017
 * Generated source version: 3.2.1
 */

@XmlRootElement(name = "shoot", namespace = "http://cc.bb.aa/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shoot", namespace = "http://cc.bb.aa/")

public class Shoot {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

